import Head from 'next/head'
import { Inter } from '@next/font/google'
import axios from 'axios';
import Nav from '../components/Nav';
import Homecom from '../components/Homecom';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const show=()=>{
    axios.get('http://localhost:3000/api/hello').then(response => {
      console.log(response.data.name);
    });
   
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Nav/>
        <Homecom/>
      </main>
    </>
  )
}
